### PR TITLE
Exercise 1 - Add loading spinner using 'cg-busy' directive

### PR DESCRIPTION
**Pull request by mauroservienti**
Replaces #97

### CODE REVIEW

**Comment by mauroservienti** [comment]
I'll change the after as well, sure. Do you want a separate PR for each exercise?

**Comment by adamralph** [comment]
> Do you want a separate PR for each exercise?

@mauroservienti your call. I don't mind either way.

**Comment by mauroservienti** [comment]
renamed PR

**Comment by mauroservienti** [comment]
exercise 1 is done @adamralph, I'll take care of others tomorrow

**Comment by mauroservienti** [comment]
thanks 😃 merging.

**Pull request merged**
