### PR TITLE
Align default namespace and assembly name with project name

### PR DESCRIPTION
**Pull request by mauroservienti**
Connects to https://github.com/Particular/Workshop.Microservices/issues/136
Fix https://github.com/Particular/Workshop.Microservices/issues/136

### CODE REVIEW

**Comment by mauroservienti** [comment]
Still need to check if there are other projects not aligned.

**Comment by mauroservienti** [comment]
Checked that namespace and assembly names are aligned. @Particular/microservices-workshop-maintainers this is good to go

**Comment by adamralph** [comment]
Needs a rebase 😢

**Comment by mauroservienti** [comment]
@adamralph rebased 😄

**Pull request merged**
