### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
image

:)

**Comment by SimonCropp** [comment]
@Particular/microservices-workshop-maintainers this is ready for review

**Comment by adamralph** [comment]
Thanks @SimonCropp - we'll get to it ASAP.

**Comment by adamralph** [comment]
Note that we should not merge this until after the TWF workshop (21st Sep).

**Comment by mauroservienti** [comment]
* rebased on master to fix conflicts.
* verified that demos and exercises work as expected
* verified that instructions are still aligned with code changes applied here (majority of changes, if not all, are to code not touched by attendees)

I'll have another look at the changes and then this should be good to go.

**Comment by mauroservienti** [comment]
@adamralph I went through all the changes. LGTM. I'm OK to merge.

**Comment by mauroservienti** [comment]
Looks good @adamralph

**Comment by mauroservienti** [comment]
👍

**Pull request merged**
