### PR TITLE
add build script

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by mauroservienti** [comment]
Can we in some way do the same thing that doco does also to configure the startup projects?

**Comment by adamralph** [comment]
> Can we in some way do the same thing that doco does also to configure the startup projects?

AFAIK that works by producing .suo files which are bundled as part of the solution downloads. Given that the attendees clone the repo in order to attempt the exercises, I don't see at what point we could generate those .suo files.

**Comment by adamralph** [comment]
@Particular/microservices-workshop-maintainers FYI I've switched on the setting to make a successful CI build mandatory for merging PR's to master.

**Comment by mauroservienti** [comment]
> AFAIK that works by producing .suo files which are bundled as part of the solution downloads. Given that the attendees clone the repo in order to attempt the exercises, I don't see at what point we could generate those .suo files.

It seems that we can provide users with a script that will be downloaded when the repo is cloned and can be run locally. I'll investigate.

**Comment by adamralph** [comment]
👍 sounds good!

**Pull request merged**
