### PR TITLE
Convert to web app

### LINKED ISSUE #20: Convert all web sites to web app
Visual Studio handles web sites very badly for the purpose of sharing exercises, making simple things much more complex than expected.
All `Divergent.Frontend.SPA` web sites, in all exercises, need to be converted from a web site to a web app.

### PR DESCRIPTION
**Pull request by mauroservienti**
This PR "simply" converts all `Web Site` projects in all the exercise solutions to `Web Application` projects, this allows to remove apllicationHost.config files from the repo, simplifying the overall usage of the exercises.

I smoke tested a couple of exercises on a clean VM. @dvdstelt @weralabaj can you please review and merge?

Fix #20

### CODE REVIEW

**Comment by weralabaj** [comment]
I smoke tested all samples, seems the conversion is ok.

I'm getting two issues though , for final solution and integration - after samples.

capture2
capture

Is that expected?

**Comment by dvdstelt** [comment]
lol, read the https://github.com/Particular/Workshop.Microservices/blob/master/faq.md ;-)

**Comment by mauroservienti** [comment]
Usual pain of post build events @weralabaj, try a clean and full rebuild.

**Comment by mauroservienti** [comment]
Question: @dvdstelt instead of post build events in VS what about adding the projects as references? It's much easier and the reason can be easily explained to attendees.

**Comment by weralabaj** [comment]
OK, good to go, sorry !

**Comment by dvdstelt** [comment]
@mauroservienti It's nearl impossible for the workshop attendees to run into this issue, because they actually write the code themselves for the providers. So if they press `F5` or `CTRL` + `F5`, they'll start a recompile of the project and trigger the post-build events.

**Pull request merged**
